In [1]:
import pandas as pd
import numpy as np

In [3]:
data1 = {
    'id' : [1,2,3],
    'name':['Mohit', 'Ankur', 'Aman'],
    'age': [22,21,25]
}

df1 = pd.DataFrame(data1)

In [4]:
df1

   id   name  age
0   1  Mohit   22
1   2  Ankur   21
2   3   Aman   25

In [5]:
data2 = {
    'id' : [1,2,3],
    'city': ['Pnb','See','hjp'],
    'Roll' :[12,18,20]
}
df2 = pd.DataFrame(data2)

In [6]:
df2

   id city  Roll
0   1  Pnb    12
1   2  See    18
2   3  hjp    20

In [8]:
Merge = pd.merge(df1,df2, on='id', how='inner')
Merge

   id   name  age city  Roll
0   1  Mohit   22  Pnb    12
1   2  Ankur   21  See    18
2   3   Aman   25  hjp    20

# Concentration

In [10]:
data3 = {
    'subject':['Phy','Che','Math'],
    'Number':[85,65,78]
}
df3 = pd.DataFrame(data3)

In [11]:
concatenated_rows = pd.concat([df2,df3])

In [12]:
concatenated_rows

    id city  Roll subject  Number
0  1.0  Pnb  12.0     NaN     NaN
1  2.0  See  18.0     NaN     NaN
2  3.0  hjp  20.0     NaN     NaN
0  NaN  NaN   NaN     Phy    85.0
1  NaN  NaN   NaN     Che    65.0
2  NaN  NaN   NaN    Math    78.0

In [13]:
concatenated_columns = pd.concat([df2,df3], axis=1)
concatenated_columns

   id city  Roll subject  Number
0   1  Pnb    12     Phy      85
1   2  See    18     Che      65
2   3  hjp    20    Math      78