In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = {
    'date': ['2001-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country' : ['USA', 'U.S.A', 'America', 'United States'],
    'name': ['Johan Doe', 'John Doe', 'Jane Doe', 'Jane Doe'],
    'sales_2020': [100,200,None,200],
    'sales_2021':[None, 150,300,150]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df.head()

         date        country       name  sales_2020  sales_2021
0  2001-12-01            USA  Johan Doe       100.0         NaN
1  01-12-2022          U.S.A   John Doe       200.0       150.0
2  2022/12/01        America   Jane Doe         NaN       300.0
3  12-01-2021  United States   Jane Doe       200.0       150.0

# Date

In [7]:
# Standarizing the date format
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df.head()

        date        country       name  sales_2020  sales_2021
0 2001-12-01            USA  Johan Doe       100.0         NaN
1        NaT          U.S.A   John Doe       200.0       150.0
2        NaT        America   Jane Doe         NaN       300.0
3        NaT  United States   Jane Doe       200.0       150.0

In [8]:
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()

         date        country       name  sales_2020  sales_2021
0  2001-12-01            USA  Johan Doe       100.0         NaN
1         NaN          U.S.A   John Doe       200.0       150.0
2         NaN        America   Jane Doe         NaN       300.0
3         NaN  United States   Jane Doe       200.0       150.0

# Assigment 
     Fill the date

In [9]:
df["date"] = df["date"].fillna(method="ffill")
df.head()

C:\Users\2005a\AppData\Local\Temp\ipykernel_23376\1822221539.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["date"] = df["date"].fillna(method="ffill")

         date        country       name  sales_2020  sales_2021
0  2001-12-01            USA  Johan Doe       100.0         NaN
1  2001-12-01          U.S.A   John Doe       200.0       150.0
2  2001-12-01        America   Jane Doe         NaN       300.0
3  2001-12-01  United States   Jane Doe       200.0       150.0

# country

In [11]:
# Harmonize the name of the country
country_mapping = {'USA': 'United States', 'U.S.A': 'United States', 'America': 'United States'}
df['country'] =  df['country'].replace(country_mapping)
df.head()

         date        country       name  sales_2020  sales_2021
0  2001-12-01  United States  Johan Doe       100.0         NaN
1  2001-12-01  United States   John Doe       200.0       150.0
2  2001-12-01  United States   Jane Doe         NaN       300.0
3  2001-12-01  United States   Jane Doe       200.0       150.0

# Name

In [12]:
# correct the typogrophical Mistake in name
df['name'] = df['name'].replace({'Johan Doe': 'John Doe'})
df.head()

         date        country      name  sales_2020  sales_2021
0  2001-12-01  United States  John Doe       100.0         NaN
1  2001-12-01  United States  John Doe       200.0       150.0
2  2001-12-01  United States  Jane Doe         NaN       300.0
3  2001-12-01  United States  Jane Doe       200.0       150.0

In [13]:
# remove duplicates 
df = df.drop_duplicates(subset="name")
df.head()

         date        country      name  sales_2020  sales_2021
0  2001-12-01  United States  John Doe       100.0         NaN
2  2001-12-01  United States  Jane Doe         NaN       300.0